config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/Contact', to:'home#show'
  get '/account', to:'user#index'
  patch '/update', to:'user#update'

  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
  post '/checkout', to: 'cart#checkout'
  get '/users/sign_out', to:'user#sign_out'
end

app/models/admin_user.rb
# app/models/admin_user.rb

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  # Define ransackable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "id_value", "phone", "updated_at"]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
 
end

app/models/home.rb
class Home < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "heading", "id", "id_value", "message", "updated_at"]
  end
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "customer_id", "id", "id_value", "order_date", "total_amount", "updated_at"]
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price", "stock_quantity", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst", "hst", "id", "id_value", "name", "pst", "updated_at"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :image
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  def add_to_cart
    session[:cart] ||= {}
    product_id = params[:product_id]
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1
    redirect_to view_cart_path, notice: 'Product added to cart successfully'
  end

  def remove_from_cart
    product_id = params[:id]
    session[:cart].delete(product_id)
    redirect_to view_cart_path, notice: 'Product removed from cart successfully'
  end

  def update_cart
    product_id = params[:product_id]
    quantity = params[:quantity][product_id].to_i
    session[:cart][product_id] = quantity if session[:cart][product_id].present?
    redirect_to view_cart_path, notice: 'Cart updated successfully'
  end

  def view_cart
    @total_price = calculate_total_price(session[:cart])
  end

  def checkout
    total_price = 0

    # Calculate total price and prepare cart hash
    session[:cart].each do |product_id, quantity|
      product = Product.find_by(id: product_id)
      if product
        price = product.price
        total_price += price * quantity
      else
        flash[:error] = "Product with ID #{product_id} not found."
        redirect_to root_path and return
      end
    end

    # Calculate taxes
    province = Province.find_by(id: current_user.province_id)
    if province
      gst = total_price * (province.gst / 100)
      pst = total_price * (province.pst / 100)
      hst = total_price * (province.hst / 100)
    else
      flash[:error] = "Province not found for the current user."
      redirect_to root_path and return
    end

    # Calculate total price including taxes
    total_with_taxes = total_price + gst + pst + hst

    # Create new order record
    order = Invoice.create(
      customer_id: current_user.id,
      total_amount: total_with_taxes,
      gst: province.gst,
      pst: province.pst,
      hst: province.hst,
    )

    # Save the order
    if order.save
      session[:cart].each do |product_id, quantity|
        Info.create(
          order_id: order.id,
          product_id: product_id,
          quantity: quantity,
          price: Product.find(product_id).price
        )
      end
      session.delete(:cart)
      redirect_to account_path
    else
      flash[:error] = "Failed to save order."
      @error = flash[:error]
    end
  end


  private

  def calculate_total_price(cart)
    total_price = 0
    if cart.present?
      cart.each do |product_id, quantity|
        product = Product.find(product_id)
        total_price += product.price * quantity
      end
    end
    total_price
  end


  def get_tax_rate_for_province(province)
    # Define tax rates for each province
    tax_rates = {
      "Alberta" => { gst: 0.05 }, # GST only
      "British Columbia" => { gst: 0.05, pst: 0.07 }, # GST and PST
      "Manitoba" => { gst: 0.05, pst: 0.07 }, # GST and PST
      "New Brunswick" => { gst: 0.05, pst: 0.10 }, # GST and HST
      "Newfoundland and Labrador" => { gst: 0.05, pst: 0.10 }, # GST and HST
      "Northwest Territories" => { gst: 0.05 }, # GST only
      "Nova Scotia" => { gst: 0.05, pst: 0.10 }, # GST and HST
      "Nunavut" => { gst: 0.05 }, # GST only
      "Ontario" => { gst: 0.05, pst: 0.08 }, # GST and PST
      "Prince Edward Island" => { gst: 0.05, pst: 0.10 }, # GST and HST
      "Quebec" => { gst: 0.05, qst: 0.09975 }, # GST and QST
      "Saskatchewan" => { gst: 0.05, pst: 0.06 }, # GST and PST
      "Yukon" => { gst: 0.05 } # GST only
    }

    # Retrieve the tax rate for the selected province
    tax_rates[province] || { gst: 0, pst: 0, qst: 0 } # Return default tax rates if province not found
  end

  def calculate_total_price_with_tax(cart)
    total_price = calculate_total_price(cart)
    province = params[:province] # Retrieve province from params (assumed to be passed during checkout)
    tax_rates = get_tax_rate_for_province(province)

    # Calculate total price with applicable taxes
    total_price_with_tax = total_price * (1 + tax_rates.values.sum)
    total_price_with_tax
  end

  def calculate_total_price_with_tax(cart)
    total_price = calculate_total_price(cart)
    province = params[:province] # Retrieve province from params (assumed to be passed during checkout)
    tax_rates = get_tax_rate_for_province(province)

    gst = total_price * tax_rates[:gst]
    pst = total_price * tax_rates[:pst].to_f
    hst = total_price * tax_rates[:hst].to_f

    total_price_with_tax = total_price + gst + pst + hst
    { total_price_with_tax: total_price_with_tax, gst: gst, pst: pst, hst: hst }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = Home.find(1)
  end
  def show
    @contact = Contact.find(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<%= @error %>

app/views/cart/remove_from_cart.html.erb
<h1>Cart#remove_from_cart</h1>
<p>Find me in app/views/cart/remove_from_cart.html.erb</p>

app/views/cart/update_cart.html.erb
<h1>Cart#update_cart</h1>
<p>Find me in app/views/cart/update_cart.html.erb</p>

app/views/cart/view_cart.html.erb
<div class="container">
    <h1 class="text-center mt-4 mb-4">Shopping Cart</h1>
    <% if session[:cart].present? %>
    <% total_price = 0 %>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <% session[:cart].each do |product_id, quantity| %>
            <tr>
                <% product = Product.find(product_id) %>
                <td><%= product.name %></td>
                <td><%= number_to_currency(product.price * quantity) %></td>
                <% total_price += (product.price * quantity) %>
                <td>
                    <%= form_tag update_cart_path(product_id), method: :patch, class: "form-inline" do %>
                        <%= hidden_field_tag :product_id, product_id %>
                        <%= number_field_tag "quantity[#{product_id}]", quantity, class: "form-control mr-2", id: "quantity_#{product_id}" %>
                        <%= submit_tag "Update", class: "btn btn-primary btn-sm" %>
                    <% end %>
                </td>
                <td>
                    <%= button_to "Remove", remove_from_cart_path(product_id), method: :delete, class: "btn btn-danger btn-sm" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <form action="<%= checkout_path %>" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="row">
            <div class="modal-body">
                <%= hidden_field_tag :id, current_user.id %>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control" value="<%= User.find(current_user.id).email %>">
                </div>
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="address" id="address" name="address" class="form-control" value="<%= User.find(current_user.id).address %>">
                </div>
                <!-- Add other form fields as needed -->
            </div>
            <%= current_user.id %>
            <div class="col-md-8 offset-md-2 text-right">
            <div class="invoice-total">
                <p><strong>Subtotal:</strong> <%= number_to_currency(total_price) %></p>
                <p><strong>GST (<%= (Province.find(User.find(current_user.id).province_id).gst)%>%) :</strong> <%= number_to_currency(total_price * (Province.find(User.find(current_user.id).province_id).gst)/100) %></p>
                <p><strong>PST (<%= (Province.find(User.find(current_user.id).province_id).pst)%>%):</strong> <%= number_to_currency(total_price * (Province.find(User.find(current_user.id).province_id).pst)/100) %></p>
                <p><strong>HST (<%= (Province.find(User.find(current_user.id).province_id).hst)%>%):</strong> <%= number_to_currency(total_price * (Province.find(User.find(current_user.id).province_id).hst)/100) %></p>
                <hr>
                <p><strong>Total:</strong> <%= number_to_currency(total_price + (total_price * (Province.find(User.find(current_user.id).province_id).gst)/100) + (total_price * (Province.find(User.find(current_user.id).province_id).pst)/100) + (total_price * (Province.find(User.find(current_user.id).province_id).hst)/100)) %></p>
            </div>
            <button type="submit" class="btn btn-primary btn-lg mt-4">Purchase Now</button>
            </div>
        </div>
    </form>
    <% else %>
    <div class="alert alert-info mt-4" role="alert">
        Your shopping cart is empty.
    </div>
    <% end %>
</div>

has context menu