config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users
  get 'cart/add_to_cart'
  get 'cart/remove_from_cart'
  get 'cart/update_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get '/Products/index', to:'products#index'
  get '/Products/show', to:'products#show'
  get '/Products/cart', to:'cart#show'
  get '/Products/cartRemove', to:'products#cartRemove'
  get '/Categories/index', to:'categories#index'
  get '/Categories/list', to:'categories#list'
  get '/Search/result', to:'search#index'
  get '/Contact', to:'home#show'
  get '/account', to:'user#index'
  patch '/update', to:'user#update'

  get '/view_cart', to: 'cart#view_cart'
  delete '/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  post '/add_to_cart', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_cart/:id', to: 'cart#update_cart', as: 'update_cart'
  post '/checkout', to: 'cart#checkout'
  get '/users/sign_out', to:'user#sign_out'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :image
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @orders = Invoice.where(customer_id: current_user.id)
  end

  def sign_out
    reset_session
    redirect_to '/', notice: 'Customer information updated successfully.'
  end

  def update
    @customer = User.find(params[:id])

    if @customer.update(customer_params)
      # Update successful, handle accordingly (e.g., redirect to another page)
      redirect_to '/account', notice: 'Customer information updated successfully.'
    else
      # Update failed, render the edit page again with error messages
      render :edit
    end
  end

  private

  def customer_params
    params.require(:user).permit(:email, :address, :province_id, :image)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <h3 class="card-header bg-primary text-white">
          User Information
        </h3>
        <div class="card-body">
          <form>
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image, class: "image" %>
            <% else %>
              <h1>No image added</h1>
            <% end %>
            <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" value="<%= @user.email %>" disabled>
            </div>
            <div class="form-group">
              <label for="address">Address</label>
              <% if @user.address.nil? %>
                <input type="text" class="form-control" id="address" value="Not added yet" disabled>
              <% else %>
                <input type="text" class="form-control" id="address" value="<%= @user.address %>" disabled>
              <% end %>
            </div>
            <div class="form-group">
              <label for="province">Province</label>
              <% if @user.province_id.nil? %>
                <input type="text" class="form-control" id="province" value="Not added yet" disabled>
              <% else %>
                <input type="text" class="form-control" id="province" value="<%= Province.find(@user.province_id).name %>" disabled>
              <% end %>
            </div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
              Edit Account
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @user, url: update_path, method: :patch do |f| %>
          <%= hidden_field_tag :id, @user.id %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :province_id %>
            <%= f.collection_select :province_id, Province.all, :id, :name, { prompt: "Select province" }, class: 'form-control' %>
          </div>
          <!-- Add other form field as needed -->
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Save changes", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <h1 class="mt-5">Orders</h1>

  <% @orders.each_with_index do |order, index| %>
    <div class="card mt-3">
      <div class="card-body">
        <h5 class="card-title">Order <%= index + 1 %></h5>
        <% order_details = Info.where(order_id: order.id) %>
        <% order_details.each do |detail| %>
          <span>Product ID: <%= detail.product_id %></span>
          <span>Quantity: <%= detail.quantity %></span>
          <span>Price: <%= detail.price * detail.quantity %></span>
          <br>
        <% end %>
        <span>GST: <%= order.gst %>% </span>
        <span>PST: <%= order.pst %>% </span>
        <span>HST: <%= order.hst %>% </span>
        <p class="card-text">Total: <%= order.total_amount %></p>
      </div>
    </div>
  <% end %>
</div>